### ISSUE TITLE
添加失败

### ISSUE THREAD

**Issue by yangzhaoyunfei** [LittleNewton/Open_Windows_Terminal_Here#2]
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2021/‎4/‎4
操作系统内部版本	19042.906
体验	Windows Feature Experience Pack 120.2212.551.0

PowerShell 7.1.3

管理员模式执行了install脚本没有添加成功

**Comment by LittleNewton** [comment]
用 pwsh.exe 执行，不要用老版本的 powershell 执行。
