### ISSUE TITLE
windows terminal preview好像不管用

### ISSUE THREAD

**Issue by Kristian-Lee** [LittleNewton/Open_Windows_Terminal_Here#3]
大佬，windows terminal preview好像不管用，提示找不到路径。windows terminal倒是完美可用。这是报错的图[https://imgtu.com/i/2g8LmF](url)

**Comment by LittleNewton** [comment]
如果是预览版，需要指定参数：

``` powershell
.\install.ps1 -PreRelease True
```

**Comment by Kristian-Lee** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by half-nothing** [comment]
错误的
![image](https://github.com/LittleNewton/Open_Windows_Terminal_Here/assets/50048293/3c8dd109-6eff-4ddc-b6ef-06a733f87638)
PreRelease 是一个切换类型的参数，所以后面不应该加True，搞了我半天，吐了

**Comment by LittleNewton** [comment]
@half-nothing 很抱歉造成的误导，应该是

``` powershell
.\install.ps1 -PreRelease
```

这部分代码不是我写的，之前的维护者已经不更新了。

**Comment by Kristian-Lee** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
