### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by abcdesteve** [LittleNewton/Open_Windows_Terminal_Here#7]
报错了
ParserError: D:\Users\abcdesteve\Desktop\uninstall.ps1:217
Line |
 217 |  … t="true" class="Header-link js-details-target btn-link">    <svg aria …
     |                                                                ~
     | The '<' operator is reserved for future use.

**Comment by LittleNewton** [comment]
经测试一切正常：
```
❯ .\install.ps1
布局风格：Mini
Found Windows Terminal version 1.16.10261.0.
Found actual executable C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe.
Windows Terminal 启动选项已添加到资源管理器右键菜单

P.S. 卸载请使用 .\uninstall.ps1 Mini
❯ pwsh -v
PowerShell 7.3.3

```

**Comment by abcdesteve** [comment]
windows11release preview确认无法正常使用，powershell版本与你相同

**Comment by LittleNewton** [comment]
> windows11release preview确认无法正常使用，powershell版本与你相同

请不要使用 Win11，本脚本与win11不兼容。

**Comment by LittleNewton** [comment]
@abcdesteve 

由于你是 Preview 版本，安装时需要指定参数：

``` powershell
.\install.ps1 -PreRelease True
```
